### PR TITLE
get fib installed immediately when the nexthop is already resolved

### PR DESCRIPTION
**Pull request by trungdtbk**

### CODE REVIEW

**Comment by anarkiwi** [comment]
This is a nice change.

Few things:

+        for controller_ip in vlan.controller_ips:
+            if ip_gw in controller_ip:
+                is_gw_valid = True
+                break
+            else:
+                continue

else:
   continue

is not necessary.

When you add/del a route, you check to see if any flows should be sent -
you can move the retrieval of the ryu DP at the same time.
flowmods = [] needs to move out a block so it is always defined.

Does it pass all tests? I think flowmod not being defined always would be a
problem.

**Comment by trungdtbk** [comment]
My intention is to check if the if the route is valid before adding the route to the route tables.

**Comment by anarkiwi** [comment]
Totally get the intention. I like it!

I'm talking about how it's done. :)

you can see, that flowmods = [] is defined in an inner block. It should be
moved out a block, so it's always defined.

**Comment by trungdtbk** [comment]
I fixed that. And it passes all the tests.

**Comment by anarkiwi** [comment]
Excellent, I merged your change. Thank you for your contribution.

**Pull request merged**
