### PR TITLE
Ryu faucet

### PR DESCRIPTION
**Pull request by shivarammysore**
1.  Changed branch name from ```packaging``` to ```ryu_faucet```
    2.  Added package name - ```org.openflowsdn.faucet```
    3.  Updated README (commercial switch support) and Architecture documents
    4.  Updated setup.py to include maintainer information

### CODE REVIEW

**Comment by KitL** [comment]
This pull request is into master. I am not going to push things into master until I  have moved the office network onto them (since our test code is not especially comprehensive). I'll try and move things across the next opportunity I get (which probably wont be until next week). You should apply it to packaging.

Re: renaming things: I will merge packaging into master after I have tested it in the office network.

It's a bit hard to see what else you have changed because the diff is against master rather than against packaging. 

Oh on the commercial switch support are you actually confident faucet will run on a pica8? I havent it for a while, but it failed miserably last time I looked at it.

**Comment by shivarammysore** [comment]
Thanks.  I like your approach.

Can you please send me the issue related to Pica8?  I will check.

Thanks & Regards

/Shivaram

**Comment by KitL** [comment]
I didnt look very deeply into it, but to my understanding the multi-table implementation on the picas is quite dodgy. I cant remember what the issue was but basically it didnt work perfectly first time and I gave up. I dont have a pica here any more to experiment with.

Also I gather noviflow can run faucet, at least that is what the guys from noviflow have told me. Unfortunately I haven't got one of those either..

**Comment by anarkiwi** [comment]
Obsoleted by directory restructure change.

**Pull request closed without merging**
