### PR TITLE
Configuration fixes and additions

### PR DESCRIPTION
**Pull request by Callum027**
Some improvements to configuration file handling.

* Fixes an infinite loop situation where include files could be recursively loaded, by keeping track of open files and logging an error (`include`) or skipping the file (`include-optional`) if an include file loop is found.

* Only commits changes an include file makes to the configuration if it was successfully loaded, by storing changes in a data structure until the end of `_dp_include()`, after all checks are done.

* Only reloads the Faucet configuration upon `SIGHUP` if changes to the configuration were found in some way. It does this when one of the following conditions are met:
  * The `FAUCET_CONFIG` environment variable has changed
  * An include file that was not loaded now exists
  * A file that has been loaded no longer exists
  * Loaded files have been changed, by comparing a SHA256 hash of the currently loaded file with the hash of the file that exists on the file system

* Adds tests to `test_config.py` to take into account the above changes.

### CODE REVIEW

**Comment by anarkiwi** [comment]
Thanks - looks like some minor conflicts during to a lot of cleaning up we
are both doing.

Would you be able to pull/resolve (should be minor).

**Comment by Callum027** [comment]
Should be good now.

**Comment by anarkiwi** [comment]
Seems to have broken tests. Would you be able to investigate please?

root@agent-p:~# more /tmp/faucet-8462.log

loading app ryu.app.ofctl_rest

loading app faucet.py

Create CustomEvent called

loading app ryu.controller.ofp_handler

instantiating app None of DPSet

creating context dpset

creating context wsgi

instantiating app ryu.app.ofctl_rest of RestStatsApi

instantiating app faucet.py of Faucet

Traceback (most recent call last):

  File "/usr/local/bin/ryu-manager", line 9, in <module>

    load_entry_point('ryu==4.6', 'console_scripts', 'ryu-manager')()

  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line
91, in

main

    services.extend(app_mgr.instantiate_apps(**contexts))

  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py",
line 50

9, in instantiate_apps

    self._instantiate(app_name, cls, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py",
line 49

5, in _instantiate

    app = cls(*args, **kwargs)

  File "/home/faucet/faucet/src/ryu_faucet/org/onfsdn/faucet/faucet.py",
line 10

1, in __init__

    self.config_hashes, dps = dp_parser(self.config_file, self.logname)

ValueError: need more than 1 value to unpack

**Comment by anarkiwi** [comment]
Apologies, I screwed up my own merge. Friday! All good.

**Pull request merged**
