### PR TITLE
Add a README for using Faucet on Aruba switches

### PR DESCRIPTION
**Pull request by abhayb-hpe**
I have written a small readme on how to go about using Faucet with Aruba switches. It talks about how to configure both the Aruba switch and faucet to make it work.

### CODE REVIEW

**Comment by shivarammysore** [comment]
@abhayb-hpe can you move this to src/docs/ directory and name this file as Readme_Aruba.rst file?  This makes our directory structure clean

**Comment by abhayb-hpe** [comment]
@shivarammysore - I can do that. Is it ok if I move it to src/docs and name it as README.Aruba.md? I see similar naming conventions for the other README files in the directory.

**Comment by shivarammysore** [comment]
You can certainly do that, but with a name - README_Aruba.md or
 README_Aruba.rst (preferred).  At some point in time, we need to move from
md to restructuredText (rst) format as it be easy to build documentation.

Thanks

**Comment by abhayb-hpe** [comment]
README_Aruba.rst it is then.

**Pull request merged**
